---
- name: Stop and remove Docker containers
  hosts: your_server
  tasks:
    - name: Stop running containers
      shell: docker stop $(docker ps -q)
      become: yes

    - name: Remove all images
      shell: docker rmi -f $(docker images -q)
      become: yes

    - name: Stop all containers
      shell: docker stop $(docker ps -aq)
      become: yes
