---
- name: Deploy Docker Container
  hosts: ppd-server
  become: true
  tasks:
    - name: Pull Latest Docker Image
      docker_image:
        name: ashishkr1703/banking:latest
        source: pull

    - name: Stop and Remove Existing Docker Container (if exists)
  docker_container:
    name: banking_container
    state: stopped
    container_default_behavior: compatibility  # Explicitly specify the value
  ignore_errors: yes  # Ignore errors if the container doesn't exist


    - name: Remove Existing Docker Container (if exists)
      docker_container:
        name: banking_container
        state: absent
      ignore_errors: yes  # Ignore errors if the container doesn't exist

    - name: Remove old Docker images
      community.general.docker_prune:
        networks: no
        containers: yes
        volumes: yes
        images: yes

    - name: Start Docker Container
      docker_container:
        name: banking_container
        image: "ashishkr1703/banking:latest"
        ports:
          - "8084:8081"
        state: started
