# ppd-ans-playbook.yml

- name: Deploy Docker Container
  hosts: ppd-server
  become: true
  tasks:
    - name: Pull Latest Docker Image
      shell: docker pull ashishkr1703/banking:latest
      
    - name: Stop and Remove Existing Docker Container
      ansible.builtin.docker_container:
        name: banking_container
        state: absent
      ignore_errors: yes

    - name: Start Docker Container
      ansible.builtin.docker_container:
        name: banking_container
        image: "ashishkr1703/banking:latest"
        ports:
          - "8084:8081"
        state: started
