- name: Stop and remove existing container
  hosts: ppd-server
  become: true
  tasks:
    - name: Stop Docker container if running
      docker_container:
        name: banking_container
        state: stopped
      ignore_errors: yes  # Ignore errors if container is not running

    - name: Remove Docker container if exists
      docker_container:
        name: banking_container
        state: absent
      ignore_errors: yes  # Ignore errors if container does not exist

- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  tasks:
    - name: Updating apt
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Install pip3
      apt:
        name: python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
        executable: pip3
        state: present

    - name: Pull Latest Docker Image from DockerHub
      command: docker pull ashishkr1703/banking:latest

    - name: Deploy Docker Container
      docker_container:
        name: banking_container
        image: "ashishkr1703/banking:latest"
        ports:
          - "8084:8081"
        state: started
