- name: Deploy Docker Container
  hosts: ppd-server
  become: true
  tasks:
    - name: Pull Latest Docker Image
      docker_image:
        name: ashishkr1703/banking:{{ DOCKER_TAG }}
        source: pull

    - name: Stop and Remove Existing Docker Container (if exists)
      docker_container:
        name: banking_container
        state: absent

    - name: Remove old Docker images
      community.general.docker_prune:
        networks: no
        containers: yes
        volumes: yes
        images: yes
        networks: yes

    - name: Start Docker Container
      docker_container:
        name: banking_container
        image: "ashishkr1703/banking:{{ DOCKER_TAG }}"
        ports:
          - "8084:8081"
        state: started

    - name: Debug
      debug:
        msg: "Deployment completed."


