- name: Deploy Docker Container
  hosts: ppd-server
  become: true
  tasks:
    - name: Pull Latest Docker Image
      docker_image:
        name: ashishkr1703/banking:{{ DOCKER_TAG }}
        source: pull

    - name: Check if container exists
      shell: docker inspect --type container banking_container
      register: docker_container_info
      ignore_errors: yes

    - name: Stop and remove existing container
      docker_container:
        name: banking_container
        state: absent
      when: docker_container_info.rc == 0

    - name: Start Docker Container
      docker_container:
        name: banking_container
        image: "ashishkr1703/banking:{{ DOCKER_TAG }}"
        ports:
          - "8084:8081"
        state: started
