- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  tasks:
    - name: Updating apt
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Pull Latest Docker Image
      docker_image:
        name: ashishkr1703/banking:latest
        source: pull

    - name: Deploy Docker Container
      docker_container:
        name: banking_container
        image: "ashishkr1703/banking:latest"
        ports:
          - "8084:8081"
        state: started
