- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  tasks:
    - name: Updating apt
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Install pip3
      apt:
        name: python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
        executable: pip3
        state: present

    - name: Deploy Docker Container
      docker_container:
        name: banking_container
        image: "ashishkr1703/banking:{{ DOCKER_TAG }}"
        ports:
          - "8084:8081"
        state: started
      notify: send_deployment_status

  handlers:
    - name: send_deployment_status
      uri:
        url: "https://api.twilio.com/2010-04-01/Accounts/your_twilio_account_sid/Messages.json"
        method: POST
        user: "your_twilio_account_sid"
        password: "your_twilio_auth_token"
        body_format: form-urlencoded
        body:
          From: "whatsapp:your_twilio_whatsapp_number"
          To: "whatsapp:recipient_whatsapp_number"
          Body: >-
            {% if status == 'OK' %}
            Deployment has been successfully done.
            {% else %}
            Something went wrong! Deployment was unsuccessful.
            {% endif %}
      when: status is defined
